Source/WaterTreatment.Web/Entities/Site.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WaterTreatment.Web.Entities
{

    public class Site : NamedEntity
    {
        public Site()
        {
            Buildings = new HashSet<Building>();
            SiteAccess = new HashSet<User>();
        }

        public string Location { get; set; }
        public bool IsActive { get; set; }
        public Nullable<DateTime> NextDigest { get; set; }

        [JsonIgnore]
        public virtual ICollection<Building> Buildings { get; set; }

        [JsonIgnore]
        public virtual ICollection<User> SiteAccess { get; set; }
    }

}

Source/WaterTreatment.Web/Controllers/SiteController.cs
using Newtonsoft.Json;
using System;
using System.Linq;
using System.Web.Mvc;
using WaterTreatment.Web.Attributes;
using WaterTreatment.Web.Entities;
using WaterTreatment.Web.Models;
using WaterTreatment.Web.Services;

namespace WaterTreatment.Web.Controllers
{

    [SectionAuthorize]
    public class SiteController : BaseController
    {


        private readonly IUserService _userService;

        public SiteController(WTContext context, IUserService userService) : base(context)
        {
            _userService = userService;
        }

        [Route("Index")]
        [Route("View")]
        public ActionResult Index()
        {

            ViewBag.SystemTypes = JsonConvert.SerializeObject(context.SystemTypes.Where(x => x.IsActive).OrderBy(x => x.Name).Select(x => new { Name = x.Name, Id = x.Id }));

            return View();
        }

        public ActionResult Create()
        {
            ViewBag.SystemTypes = JsonConvert.SerializeObject(context.SystemTypes.Where(x => x.IsActive).OrderBy(x => x.Name).Select(x => new { Name = x.Name, Id = x.Id }));

            return View(new SiteModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SiteModel model)
        {
            var trimmedName = model.Name.Trim().ToLower();
            var nameExists = context.Sites.Any(s => s.Name.Trim().ToLower() == trimmedName);

            if (ModelState.IsValid && !nameExists)
            {

                var newSite = new Site { Name = model.Name, Location = model.Location, IsActive = model.IsActive };

                foreach(var b in model.Buildings)
                {

                    var newBuilding = new Building { Name = b.Name, BuildingNumber = b.BuildingNumber, RPSUID = b.RPSUID, RPUID = b.RPUID, IsActive = b.IsActive };

                    foreach (var s in b.Systems)
                    {
                        var systemType = context.SystemTypes.First(x => x.Id == s.SystemTypeId);
                        newBuilding.Systems.Add(new BuildingSystem { Location = s.Location, Description = s.Description, SystemType = systemType });
                    }

                    newSite.Buildings.Add(newBuilding);

                }

                context.Sites.Add(newSite);
                context.SaveChanges();

                TempData["CreateSuccess"] = model.Name + " was created successfully";
                return RedirectToAction("Index");

            }

            if (nameExists) {
                ModelState.AddModelError("", String.Format("A site with the name {0} already exists.  Please choose a unique site name.", model.Name));
                ViewBag.Data = JsonConvert.SerializeObject(model);
            }

            ViewBag.SystemTypes = JsonConvert.SerializeObject(context.SystemTypes.OrderBy(x => x.Name).Select(x => new { Name = x.Name, Id = x.Id }));
            return View(model);

        }

        [HttpGet]
        public ActionResult Edit(int Id = 0)
        {

            var site = context.Sites.FirstOrDefault(x => x.Id == Id);

            if (site == null)
            {
                TempData["Error"] = "Invalid Id";
                return RedirectToAction("Index");
            }

            if (!_userService.CanEditSite(site))
            {
                TempData["Error"] = "You do not have permisson to edit this site.";
                return RedirectToAction("Index");
            }

            var siteModel = new SiteModel { Id = site.Id, Name = site.Name, Location = site.Location, IsActive = site.IsActive };

            foreach (var b in site.Buildings)
            {

                var newBuilding = new BuildingModel
                {
                    Id = b.Id,
                    Name = b.Name,
                    BuildingNumber = b.BuildingNumber,
                    RPUID = b.RPUID,
                    RPSUID = b.RPSUID,
                    IsActive = b.IsActive
                    
                };

                foreach (var s in b.Systems)
                {
                    if (s.IsActive)
                    {
                        newBuilding.Systems.Add(new BuildingSystemModel { Id = s.Id, Location = s.Location, Description = s.Description, SystemTypeId = s.SystemType.Id });
                    }
                }

                siteModel.Buildings.Add(newBuilding);

            }

            ViewBag.SystemTypes = JsonConvert.SerializeObject(context.SystemTypes.OrderBy(x => x.Name).Select(x => new { Name = x.Name, Id = x.Id, IsActive = x.IsActive }));
            ViewBag.Data = JsonConvert.SerializeObject(siteModel); 

            return View();

        }

        [HttpPost]
        [ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(SiteModel Model)
        {
            var trimmedName = Model.Name.Trim().ToLower();
            var nameExists = context.Sites.Any(s => s.Id != Model.Id && s.Name.Trim().ToLower() == trimmedName);
            if (ModelState.IsValid && !nameExists)
            {

                var site = context.Sites.FirstOrDefault(x => x.Id == Model.Id);

                if (site == null)
                {
                    TempData["Error"] = "Invalid Id";
                    return RedirectToAction("Index");
                }

                if (!_userService.CanEditSite(site))
                {
                    TempData["Error"] = "You do not have permisson to edit this site.";
                    return RedirectToAction("Index");
                }

                site.Name = Model.Name;
                site.Location = Model.Location;
                site.IsActive = Model.IsActive;

                var ToRemove = site.Buildings.Where(x => !Model.Buildings.Any(y => y.Id == x.Id)).ToList();
                var ToUpdate = site.Buildings.Where(x => Model.Buildings.Any(y => y.Id == x.Id)).ToList();
                var ToAdd = Model.Buildings.Where(x => !site.Buildings.Any(y => y.Id == x.Id)).ToList();

                //Remove buildings that no longer exist
                foreach (var b in ToRemove)
                    site.Buildings.Remove(b);

                //Update any existing buildings
                foreach (var b in ToUpdate)
                {

                    var NewData = Model.Buildings.First(x => x.Id == b.Id);

                    b.Name = NewData.Name;
                    b.BuildingNumber = NewData.BuildingNumber;
                    b.RPSUID = NewData.RPSUID;
                    b.RPUID = NewData.RPUID;
                    b.IsActive = NewData.IsActive;

                    var ToRemoveSystems = b.Systems.Where(x => !NewData.Systems.Any(y => y.Id == x.Id)).ToList();
                    var ToUpdateSystems = b.Systems.Where(x => NewData.Systems.Any(y => y.Id == x.Id && ( y.Location != x.Location || y.Description!= x.Description || y.SystemTypeId != x.SystemType.Id))).ToList();
                    var ToAddSystems = NewData.Systems.Where(x => !b.Systems.Any(y => y.Id == x.Id)).ToList();

                    //Remove BuildingSystems that no longer exist
                    foreach (var s in ToRemoveSystems)
                    {
                        //Remove BuildingSystem(s);
                        s.Location = s.Location;
                        s.Description = s.Description;
                        s.SystemType = s.SystemType;
                        s.UpdateDate = DateTime.Now;
                        s.IsActive = false;
                        s.Users = null;
                    }

                    //Update any existing BuildingSystems
                    foreach (var s in ToUpdateSystems)
                    {
                        var NewSystemData = NewData.Systems.First(x => x.Id == s.Id);
                        var siteReports = context.Reports.Where(r=>r.Site.Id == s.Building.Site.Id && r.SubmissionDate !=null);
                        if (siteReports.Count() > 0)
                        {
                            //add new system type
                            b.Systems.Add(new BuildingSystem { Location = NewSystemData.Location, Description = NewSystemData.Description, SystemType = context.SystemTypes.First(x => x.Id == NewSystemData.SystemTypeId), IsActive = true, CreateDate = DateTime.Now });
                            //update current sys type
                            s.IsActive = false;
                            s.UpdateDate = DateTime.Now;
                        }
                        else
                        {
                            s.Location = NewSystemData.Location;
                            s.Description = NewSystemData.Description;
                            s.SystemType = context.SystemTypes.First(x => x.Id == NewSystemData.SystemTypeId);
                            s.IsActive = true;
                            s.UpdateDate = DateTime.Now;
                        }
                    }

                    //Add any new BuildingSystems
                    foreach (var s in ToAddSystems)
                    {
                        var systemType = context.SystemTypes.First(x => x.Id == s.SystemTypeId);
                        b.Systems.Add(new BuildingSystem { Location = s.Location, Description = s.Description, SystemType = systemType, IsActive = true, CreateDate = DateTime.Now});
                    }

                    
                    //foreach (var system in b.Systems.Where(bs => bs.Id == 0))
                    //{
                    //    foreach (var access in site.Access)
                    //    {
                    //        access.BuildingSystems.Add(system);
                    //    }
                    //}

                }

                //Add any new buildings
                foreach (var b in ToAdd)
                {

                    var newBuilding = new Building { Name = b.Name, BuildingNumber = b.BuildingNumber, RPSUID = b.RPSUID, RPUID = b.RPUID, IsActive = b.IsActive };

Source/WaterTreatment.Web/Views/Site/Create.cshtml
@model WaterTreatment.Web.Models.SiteModel
@{
    ViewBag.Title = "Create Site";
}
@Html.Partial("_CreateEdit", Model)
@section Scripts
{
<script type="text/javascript">
require(['jquery', 'knockout', 'App/ViewModels/Site/site', 'koVal'], function($, ko, ViewModel) {
    @if (ViewBag.Data != null) {
    <text>
    var vm = new ViewModel(@Html.Raw(ViewBag.SystemTypes), @Html.Raw(ViewBag.Data));
    </text>
    } else {
            <text>
    var vm = new ViewModel(@Html.Raw(ViewBag.SystemTypes));
    </text>
    }



    $(document).ready(function () {
        window.onbeforeunload = function () {
            if (vm.isDirty()) {
                return 'You have unsaved changes. Are you sure you wish to leave this page?';
            }
        };

        ko.applyBindingsWithValidation(vm, document.getElementById('createPage'), {
            errorMessageClass: 'text-danger',
            decorateInputElement: true,
            errorElementClass: 'has-error'
        });
    });
});
</script>
}

Source/WaterTreatment.Web/Views/Site/Edit.cshtml
@model WaterTreatment.Web.Models.SiteModel
@{
    ViewBag.Title = "Edit Site";
}
@Html.Partial("_CreateEdit", Model)
@section Scripts
{
    <script type="text/javascript">
require(['jquery', 'knockout', 'App/ViewModels/Site/site', 'koVal'], function($, ko, ViewModel) {
    var vm = new ViewModel(@Html.Raw(ViewBag.SystemTypes), @Html.Raw(ViewBag.Data));

    $(document).ready(function () {
        window.onbeforeunload = function () {
            if (vm.isDirty()) {
                return 'You have unsaved changes. Are you sure you wish to leave this page?';
            }
        };

        ko.applyBindingsWithValidation(vm, document.getElementById('createPage'), {
            errorMessageClass: 'text-danger',
            decorateInputElement: true,
            errorElementClass: 'has-error'
        });
    });
});
    </script>
}

Source/WaterTreatment.Web/Views/Site/Index.cshtml
@{
    ViewBag.Title = "Site Configuration";
}
<div class="container-fluid" style="padding-top: 1.0em" id="knockout-area">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="form-group col-md-2">
                    <label>Name</label>
                </div>
                <div class="form-group col-md-4">
                    <input type="text" id="Name" class="form-control" data-bind="textInput: filters.Name" placeholder="Name" />
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-2">
                    <label>Location</label>
                </div>
                <div class="form-group col-md-4">
                    <input type="text" id="Location" class="form-control" data-bind="textInput: filters.Location" placeholder="Location" />
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-2">
                    <label>Building Name</label>
                </div>
                <div class="form-group col-md-4">
                    <input type="text" id="BuildingName" class="form-control" data-bind="textInput: filters.BuildingName" placeholder="Building Name" />
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-2">
                    <label>System Type</label>
                </div>
                <div class="form-group col-md-4">
                    <select class="form-control systemSelect" multiple="multiple" data-bind="options: systemTypes, selectedOptions: filters.SystemTypes, optionsText: 'Name', optionsValue: 'Id', multiselect: {
                    maxHeight: 400,
                    includeSelectAllOption: true,
                    enableFiltering: true,
                    filterBehavior: 'text',
                    enableCaseInsensitiveFiltering: true,
                    nonSelectedText: 'Any',
                    numberDisplayed: 1,
                    buttonWidth: '100%'
                }"></select>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-2">
                    <label>Is Active</label>
                </div>
                <div class="form-group col-md-4">
                    <div class="btn-group" data-toggle="buttons">
                        <label class="btn btn-default active">
                            <input type="radio" name="type" value="true" data-bind="checked: filters.IsActive, bsChecked: filters.IsActive" />Active
                        </label>
                        <label class="btn btn-default">
                            <input type="radio" name="type" value="false" data-bind="checked: filters.IsActive, bsChecked: filters.IsActive" />Inactive
                        </label>
                        <label class="btn btn-default">
                            <input type="radio" name="type" value="all" data-bind="checked: filters.IsActive, bsChecked: filters.IsActive" />All
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="inset-container row">
            <div class="pager-row">
                @Html.Partial("_PagerControls")
                <div class="pull-left form-inline" style="margin-top: 1em;">
                    <span class="form-group pager-text"><strong>Sites</strong> <span style="display: none;" data-bind="visible: pager.totalResults() > 0">(<span data-bind="text: pager.totalResults"></span>)</span></span>
                </div>
            </div>
            <div style="position: relative">
                @Html.Partial("_PagerSpinner")
                <table class="table striped-grid">
                    <thead>
                        <tr class="branded-header">
                            <th>
                                <a href="#" data-bind="click: function() { pager.sort('Name') }">Name</a>
                                <i data-bind="attr: { class: pager.sortArrow('Name') }"></i>
                            </th>
                            <th>
                                <a href="#" data-bind="click: function() { pager.sort('Location') }">Location</a>
                                <i data-bind="attr: { class: pager.sortArrow('Location') }"></i>
                            </th>
                            <th>
                                <a href="#" data-bind="click: function() { pager.sort('BuildingCount') }">Building Count</a>
                                <i data-bind="attr: { class: pager.sortArrow('BuildingCount') }"></i>
                            </th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody data-bind="foreach: { data: sites, as: '$site' }">
                        <tr>
                            <td class="col-lg-6">
                                <a data-bind="text: $site.name, attr: { href: $site.getEditUrl }"></a>
                            </td>
                            <td class="col-lg-2" data-bind="text: $site.location" />
                            <td class="col-lg-2" data-bind="text: $site.buildingCount" />
                            <td class="col-lg-2">
                                <div style="position: relative">
                                    <button type="button" class="btn btn-sm fa fa-edit site-actions-edit" data-bind="disable: $root.isProcessingRequest, click: function() { $site.edit($root.isProcessingRequest); }"></button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div>
                @Html.Partial("_PagerControls")
            </div>
        </div>
    </div>
</div>
@section Scripts
{
    <script type="text/javascript">
require(['jquery', 'knockout', 'App/ViewModels/Site/index', 'bootstrap'], function ($, ko, siteViewModel) {

    $(document).ready(function () {
        ko.applyBindings(new siteViewModel(@Html.Raw(ViewBag.SystemTypes)), $('#knockout-area')[0]);
    });

});
    </script>
}

Source/WaterTreatment.Web/Views/Site/_CreateEdit.cshtml
@model WaterTreatment.Web.Models.SiteModel
<div class="container-fluid" id="createPage" style="display: none;" data-bind="visible: true">
    @using (Html.BeginForm("Create", "Site", new { }, FormMethod.Post, new { @class = "form-horizontal", id = "createForm" }))
    {
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.AntiForgeryToken()
        <div class="form-group alert alert-warning" style="margin-top:25px; margin-bottom:25px;" data-bind="visible: isDirty">
            <span>
                Buildings and systems that are in edit mode are not saved. You must click ok and then click save to persist the data.
            </span>
        </div>
        <div class="form-group">
            @Html.Label("Site Name", new { @class = "col-md-2 control-label" })
            <div class="col-md-10" data-bind="validationElement: $data.name">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", data_bind = "textInput: $data.name" })
                @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Location, new { @class = "col-md-2 control-label" })
            <div class="col-md-10" data-bind="validationElement: $data.location">
                @Html.TextBoxFor(m => m.Location, new { @class = "form-control", data_bind = "textInput: $data.location" })
                @Html.ValidationMessageFor(m => m.Location, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label">Is Active</label>
            <div class="col-md-10" data-bind="validationElement: $data.isActive">
                <div class="btn-group" data-toggle="buttons">
                    <label class="btn btn-default active">
                        <input type="radio" name="type" value="true" data-bind="checked: isActive, bsChecked: isActive" />Active
                    </label>
                    <label class="btn btn-default">
                        <input type="radio" name="type" value="false" data-bind="checked: isActive, bsChecked: isActive" />Inactive
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Buildings, new { @class = "col-md-2 control-label" })
            <div class="col-md-10" data-bind="foreach: { data: $data.buildings, as: '$building' }">
                <!-- ko ifnot: $building.inEditMode -->
                <div class="form-control-static">
                    <span data-bind="text: $building.name"></span>
                    <a href="#" role="button" data-bind="click: edit">Edit</a>
                    <a href="#" role="button" data-bind="click: $parent.removeBuilding">Remove</a>
                </div>
                <div data-bind="foreach: { data: $building.systems, as: '$system' }">
                    <!-- ko if: $system.inEditMode -->
                    <div class="col-md-offset-1">
                        <div class="form-group">
                            <label class="col-md-2 control-label">System Type</label>
                            <div class="col-md-10">
                                <select class="form-control systemSelect" data-bind="options: $root.activeSystemTypes, value: $system.systemType, optionsText: 'Name', optionsValue: 'Id', multiselect: {
                                    maxHeight: 400,
                                    includeSelectAllOption: false,
                                    enableFiltering: true,
                                    filterBehavior: 'text',
                                    enableCaseInsensitiveFiltering: true,
                                    buttonWidth: '300px'
                                }"></select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label">Measurement Location</label>
                            <div class="col-md-10" data-bind="validationElement: $system.location">
                                <input type="text" required class="form-control" data-bind="textInput: $system.location" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label">Description</label>
                            <div class="col-md-10" data-bind="validationElement: $system.description">
                                <input type="text" required class="form-control" data-bind="textInput: $system.description" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-1 form-control-static">
                                <a href="#" role="button" data-bind="text: $system.saveLabel, click: $system.save"></a>
                            </div>
                            <div class="col-md-1 form-control-static">
                                <a href="#" role="button" data-bind="click: $building.cancelSystem">Cancel</a>
                            </div>
                        </div>
                    </div>
                    <!-- /ko -->
                    <!-- ko ifnot: $system.inEditMode -->
                    <div class="form-control-static col-md-offset-1">
                        <div class="row">
                            <span data-bind="text: $system.displayName"></span>
                            <a href="#" role="button" data-bind="click: $system.edit">Edit</a>
                            <a href="#" role="button" data-bind="click: $parent.removeSystem">Remove</a>
                        </div>                        
                        <div class="row" style="padding-bottom: 1.0em">
                            <label class="control-label">Description</label>
                            <span data-bind="text: $system.description"></span>
                        </div>
                    </div>
                    <!-- /ko -->
                </div>
                <div class="form-control-static col-md-offset-1">
                    <a href="#" role="button" data-bind="visible: $root.systemTypes.length > 0, click: addSystem">Add System</a>
                </div>
                <!-- /ko -->
                <!-- ko if: $building.inEditMode -->
                <div class="form-group">
                    <label class="col-md-2 control-label">Building Name</label>
                    <div class="col-md-8" data-bind="validationElement: $building.name">
                        <input type="text" required class="form-control" data-bind="textInput: $building.name" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">Is Active</label>
                    <div class="col-md-8" data-bind="validationElement: $data.isActive">
                        <div class="btn-group" data-toggle="buttons">
                            <label class="btn btn-default active">
                                <input type="radio" name="type" value="true" data-bind="checked: isActive, bsChecked: isActive" />Active
                            </label>
                            <label class="btn btn-default">
                                <input type="radio" name="type" value="false" data-bind="checked: isActive, bsChecked: isActive" />Inactive
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">Building Number</label>
                    <div class="col-md-8">
                        <input type="text" required class="form-control" data-bind="textInput: $building.number" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">RPUID</label>
                    <div class="col-md-8">
                        <input type="text" required class="form-control" data-bind="textInput: $building.RPUID" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">RPSUID</label>
                    <div class="col-md-8">
                        <input type="text" required class="form-control" data-bind="textInput: $building.RPSUID" />
                    </div>
                    <div class="col-md-1 form-control-static">
                        <a href="#" role="button" data-bind="text: $building.saveLabel, click: $building.save"></a>
                    </div>
                    <div class="col-md-1 form-control-static">
                        <a href="#" role="button" data-bind="click: $parent.cancelBuilding">Cancel</a>
                    </div>
                </div>
                <!-- /ko -->
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-2" data-bind="validationElement: $data.buildings">
                <a href="#" role="button" data-bind="click: $data.addBuilding">Add Building</a>
                <div class="text-danger" data-bind="validationMessage: $data.buildings"></div>
            </div>
            <div class="col-md-6">
                <button type="button" class="btn btn-default pull-right" data-bind="click: $data.save, disable: $root.isProcessingRequest() || !$root.isValid()">Save Site</button>
            </div>
        </div>
    }
</div>