Source/WaterTreatment.Web/Controllers/DataEntryController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;
using WaterTreatment.Web.Attributes;
using WaterTreatment.Web.Entities;
using WaterTreatment.Web.Extensions;
using WaterTreatment.Web.Models;
using WaterTreatment.Web.Services;
using WaterTreatment.Web.Services.Interface;
using Newtonsoft.Json;
using System.Data.SqlClient;
using System.Data;

namespace WaterTreatment.Web.Controllers
{

    [SectionAuthorize]
    public class DataEntryController : BaseController
    {
        private readonly UserManager<User, int> userManager;
        private readonly IAWSS3 _s3Storage;
        private readonly IFileStorage _storage;
        private readonly IUserService _userService;
        private readonly IReportService _reportService;

        public DataEntryController(WTContext context, UserManager<User, int> userManager, IUserService userService, IReportService reportService, IFileStorage storage, IAWSS3 s3Storage)
            : base(context)
        {
            this.userManager = userManager;
            _storage = storage;
            _userService = userService;
            _reportService = reportService;
            _s3Storage = s3Storage;
        }

        public ActionResult Index()
        {

            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {

            var isDataRecorder = CurrentUser.Roles.Any(x => x.RoleId == context.Ref.Roles.DataRecorder.Id);
            var isAuditRecorder = CurrentUser.Roles.Any(x => x.RoleId == context.Ref.Roles.AuditRecorder.Id);
            var isAdmin = CurrentUser.Roles.Any(x => x.RoleId == context.Ref.Roles.SystemAdministrator.Id);

            if ((isDataRecorder && isAuditRecorder) || isAdmin || _userService.IsSiteAdmin())
                ViewBag.HasMultipleUse = true;

            var allowedSites = _userService.GetActiveSites();

            ViewBag.Sites = allowedSites.Select(x => new { Id = x.Id, Name = x.Name }).OrderBy(s => s.Name).ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ReportStartModel Model)
        {

            var isDataRecorder = CurrentUser.Roles.Any(x => x.RoleId == context.Ref.Roles.DataRecorder.Id);
            var isAuditRecorder = CurrentUser.Roles.Any(x => x.RoleId == context.Ref.Roles.AuditRecorder.Id);
            var isAdmin = _userService.IsAdmin() || _userService.IsSiteAdmin();

            if (ModelState.IsValid)
            {
                var site = context.Sites.FirstOrDefault(x => x.Id == Model.SiteId);

                if (site != null)
                {
                    var R = new Report();

                    R.User = CurrentUser;
                    R.Site = site;
                    R.CreationDate = DateTime.UtcNow;
                    R.SubmissionDate = null;

                    var userId = CurrentUser.Id;

                    if ((isDataRecorder && isAuditRecorder) || isAdmin)
                        R.ReportType = Model.Use;
                    else if (isDataRecorder)
                        R.ReportType = "Measurement";
                    else if (isAuditRecorder)
                        R.ReportType = "Independent Quality Assurance";

                    foreach (var building in site.Buildings.Where(x => x.IsActive))
                    {
                        //var BR = new BuildingReport();
                        //BR.Building = building;

                        //Admins can access everything, otherwise filter based on user access
                        foreach (var system in building.Systems.Where(x => isAdmin || x.Users.Any()))
                        {
                            if (!system.IsActive)
                            {
                                continue;
                            }
                            var SM = new SystemMeasurement();
                            SM.BuildingSystem = system;

                            foreach (var parameter in system.SystemType.Parameters.Where(x => x.Use == R.ReportType || x.Use == "Both"))
                            {
                                var M = new Measurement();
                                M.Value = String.Empty;
                                M.Comment = String.Empty;
                                M.Parameter = parameter;
                                M.IsApplicable = true;
                               // M.Parameter.AltParameter = -1;
                                SM.Measurements.Add(M);
                            }

                            if (SM.Measurements.Any())
                            {
                                R.SystemMeasurements.Add(SM);
                            }
                        }

                        //if (BR.SystemMeasurements.Any())
                        //{
                        //    R.SystemMeasurements.Add(BR);
                        //}
                    }
                    context.Reports.Add(R);
                    context.SaveChanges();
                    return RedirectToAction("Edit", new { Id = R.Id });
                }
                else
                {
                    ModelState.AddModelError("SiteId", "The selected site does not exist.");
                }
            }


            if ((isDataRecorder && isAuditRecorder) || isAdmin)
                ViewBag.HasMultipleUse = true;

            var allowedSites = _userService.GetActiveSites();

            ViewBag.Sites = allowedSites.Select(x => new { Id = x.Id, Name = x.Name }).ToList();
            return View();
        }

        private bool IsNumeric(string input)
        {
            bool returnVal = false;
            int testInt;
            float testFloat;
            returnVal = int.TryParse(input, out testInt)||float.TryParse(input, out testFloat);
            return returnVal;
        }

        private void SaveReport(Report Report, ReportModel Model)
        {
            Report.MeasurementDate = DateTime.Parse(Model.MeasurementDate);
            Report.Notes = Model.Notes;

            foreach (var b in Model.Buildings)
            {
                //var BR = Report.SystemMeasurements.First(x => x.Id == b.Id);  // todo
                foreach (var s in b.Systems)
                {
                    var SM = Report.SystemMeasurements.First(x => x.Id == s.Id);
                    int buildingSystemId = SM.BuildingSystem.Id;

                    if (!string.IsNullOrEmpty(s.ReasonSkipped))
                    {
                        SM.ReasonSkipped = s.ReasonSkipped;
                    }
                    else
                    {
                        SM.ReasonSkipped = s.ReasonSkipped;

                        foreach (var m in s.Measurements)
                        {
                            if (m.IsAdhoc)
                            {
                                int typeVal = IsNumeric(m.Value) ? 2 : 1;
                                var AHP = SaveAdhocParameter(m.Unit, m.Source, m.Name, typeVal, buildingSystemId);
                                if ((typeVal == 2) && (m.MinValue != null || m.MaxValue != null))
                                {
                                    SaveParameterBound(m.Range, "Value", m.MinValue, m.MaxValue, AHP);
                                }
                                SaveAdhocMeasurement(m.Value, m.Comment, AHP, SM.Id);
                            }
                            else
                            {
                                var measurement = SM.Measurements.First(x => x.Id == m.Id);
                                measurement.Value = m.Value;
                                measurement.IsApplicable = m.IsApplicable;
                                measurement.Comment = m.Comment;
                                BakeOOB(measurement, Report);
                            }
                        }
                    }
                }
            }

            context.SaveChanges();
        }

        private AdhocParameter SaveAdhocParameter(string unit, string source, string name, int type, int buildingSystemId)
        {
            AdhocParameter ahp = context.AdhocParameters.FirstOrDefault(x => x.BuildingSystem.Id == buildingSystemId && x.Name == name && x.Source == source);
            if (ahp == null)
            {
                ahp = new AdhocParameter();
                ahp.Unit = unit;
                ahp.Source = source;
                ahp.Name = name;
                ahp.Type = context.ParameterTypes.FirstOrDefault(PR => PR.Id == type);
                ahp.BuildingSystem = context.BuildingSystems.FirstOrDefault(x => x.Id == buildingSystemId);
                context.AdhocParameters.Add(ahp);
            }
            else
            {
                ahp.Unit = unit;
                ahp.Source = source;
                ahp.Name = name;
            }
            return ahp;
        }

        private void SaveParameterBound(string range, string type, decimal? minValue, decimal? maxValue, AdhocParameter adhocParameter)
        {
            ParameterBound APB = adhocParameter.ParameterBounds.FirstOrDefault();
            if (APB == null)
            {
                APB = new ParameterBound();
                APB.IsEnforced = true;
                APB.MaxValue = maxValue;
                APB.MinValue = minValue;
                APB.Type = type;
                APB.Range = range;
                APB.AdhocParameter = adhocParameter;
                adhocParameter.ParameterBounds.Add(APB);
            }
            else
            {
                APB.IsEnforced = true;
                APB.MaxValue = maxValue;
                APB.MinValue = minValue;
                APB.Type = type;
                APB.Range = range;
                APB.AdhocParameter = adhocParameter;
            }
        }

Source/WaterTreatment.Web/Views/DataEntry/CopyReport.cshtml
@using WaterTreatment.Web.Models
@{
    ViewBag.Title = "Copy report";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userInfo = ViewData["UserInfo"] as UserInfoModel;
}
<div class="container-fluid" style="padding-top: 1.0em" id="knockout-area">

    <div class="row space-bottom-full">
        <div class="row">
            <div class="col-md-3">
                <label>Report Site</label>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <select class="form-control" multiple="multiple" data-bind="options: sites, selectedOptions: filters.Sites, optionsText: 'Name', optionsValue: 'Id', multiselect: msOptions"></select>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="inset-container row">
            <div class="pager-row">
                @Html.Partial("_PagerControls")
                <div class="pull-left form-inline" style="margin-top: 1em;">
                    <span class="form-group pager-text"><strong>Submitted Reports</strong> <span style="display: none;" data-bind="visible: pager.totalResults() > 0">(<span data-bind="text: pager.totalResults"></span>)</span></span>
                </div>
            </div>
            <div>
                @Html.Partial("_PagerSpinner")
                <table class="table striped-grid">
                    <thead>
                        <tr class="branded-header">
                            <th>
                                <a href="#" data-bind="click: function() { pager.sort('Site') }">Site</a>
                                <i data-bind="attr: { class: pager.sortArrow('Site') }"></i>
                            </th>
                            <th>
                                <a href="#" data-bind="click: function() { pager.sort('Type') }">Type</a>
                                <i data-bind="attr: { class: pager.sortArrow('Type') }"></i>
                            </th>
                            <th>
                                <a href="#" data-bind="click: function() { pager.sort('StartedOn') }">Started</a>
                                <i data-bind="attr: { class: pager.sortArrow('StartedOn') }"></i>
                            </th>
                            <th>
                                <a href="#" data-bind="click: function() { pager.sort('MeasuredOn') }">Measured</a>
                                <i data-bind="attr: { class: pager.sortArrow('MeasuredOn') }"></i>
                            </th>
                            <th>
                                <a href="#" data-bind="click: function() { pager.sort('SubmittedOn') }">Submitted</a>
                                <i data-bind="attr: { class: pager.sortArrow('SubmittedOn') }"></i>
                            </th>
                            <th data-bind="visible: showCreatedBy" style="display: none;">Created By</th>
                            <th data-bind="visible: showCreatedBy" style="display: none;">Vendor</th>
                            <th colspan="2">Actions</th>
                        </tr>
                    </thead>
                    <tbody data-bind="foreach: { data: reports, as: '$report' }">
                        <tr data-bind="css: {'danger': $report.DaysElapsed > 7}">
                            <td class="grid-cell">
                                <a title="View report" data-bind="attr: { 'href': '/Reports/View/' + $report.Id }"><span data-bind="text: $report.Site"></span></a>
                            </td>
                            <td class="grid-cell">
                                <span data-bind="text: $report.Type"></span>
                            </td>
                            <td class="grid-cell">
                                <span data-bind="text: $report.StartedOn"></span>
                            </td>
                            <td class="grid-cell">
                                <span data-bind="text: $report.MeasuredOn"></span>
                            </td>
                            <td class="grid-cell">
                                <span data-bind="text: $report.SubmittedOn"></span>
                            </td>
                            <td class="grid-cell" data-bind="visible: $root.showCreatedBy" style="display: none;">
                                <span data-bind="text: $report.CreatedBy"></span>
                            </td>
                            <td class="grid-cell" data-bind="visible: $root.showCreatedBy" style="display: none;">
                                <span data-bind="text: $report.Vendor"></span>
                            </td>
                            <!-- ko if: $root.showAdminActions -->
                            <td class="grid-cell" data-bind="visible: $root.showCreatedBy" style="display: none;">
                                <div style="position: relative">
                                    <div class="report-actions-unsubmit" style="text-align: center; width: 100%" data-bind="css: { 'has-requested-unsubmit': $report.HasRequestedUnsubmit }">
                                        <button class="btn btn-sm" data-bind="click: $root.copyReport ">Copy Report</button>
                                    </div>
                                </div>
                            </td>
                            <!-- /ko -->
                        </tr>
                    </tbody>
                </table>
                <div class="alert-success" data-bind="text: $root.successMessage"></div>
            </div>
            <div>
                @Html.Partial("_PagerControls")
            </div>
        </div>
    </div>
    @Html.Partial("_Modal")
    @Html.AntiForgeryToken()
</div>
@section Scripts
{
    <script type="text/javascript">
        require(['jquery', 'knockout', 'App/ViewModels/DataEntry/CopyReport', 'bootstrap', 'bootstrap-multiselect', 'bootstrap-datepicker'], function ($, ko, ViewModel) {
            $(document).ready(function () {
                ko.applyBindings(new ViewModel(@Html.Raw(ViewBag.Sites), @Html.Raw(ViewBag.InitialState)), $('#knockout-area')[0]);
            });
        });
    </script>
}

Source/WaterTreatment.Web/Views/DataEntry/Create.cshtml
@{
    ViewBag.Title = "Start Report";
}
<div class="container-fluid" id="knockoutArea" style="display: none;" data-bind="visible: true">
    @using (Html.BeginForm("Create", "DataEntry", new { }, FormMethod.Post, new { @class = "form-horizontal", id = "createForm" }))
    {
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.AntiForgeryToken()
        <div class="container">
            <table>
                <tr>
                    <td>
                        <h4>Report Site</h4>
                    </td>
                    @if (ViewBag.HasMultipleUse != null && ViewBag.HasMultipleUse)
                    {
                        <td style="padding-left: 20px;">
                            <h4>Report Type</h4>
                        </td>
                    }
                </tr>
                <tr>
                    <td>
                        <select name="SiteId" class="form-control" data-bind="options: $root.sites, value: siteId, optionsText: 'Name', optionsValue: 'Id', multiselect: {
                            maxHeight: 400,
                            includeSelectAllOption: false,
                            enableFiltering: true,
                            filterBehavior: 'text',
                            enableCaseInsensitiveFiltering: true,
                            buttonWidth: '300px' }">
                        </select>
                    </td>
                    @if (ViewBag.HasMultipleUse != null && ViewBag.HasMultipleUse)
                    {
                        <td style="padding-left: 20px;">
                            <div class="btn-group" data-toggle="buttons">
                                <label class="btn btn-default active">
                                    <input type="radio" name="Use" value="Measurement" data-bind="checked: use, bsChecked: use" />Measurement
                                </label>
                                <label class="btn btn-default">
                                    <input type="radio" name="Use" value="Independent Quality Assurance" data-bind="checked: use, bsChecked: use" />Independent Quality Assurance
                                </label>
                            </div>
                        </td>
                    }
                    <td style="padding-left: 20px;">
                        <button type="button" class="btn btn-primary" data-bind="disable: isProcessingRequest, click: create">Start Report</button>
                    </td>
                </tr>
            </table>
        </div>
    }
</div>
@section Scripts
{
    <script type="text/javascript">
    require(["jquery", "knockout", "App/ViewModels/DataEntry/create"], function($, ko, ViewModel) {

        var vm = new ViewModel(@Html.Raw(Json.Encode(ViewBag.Sites)));

        $(document).ready(function () {

            ko.applyBindings(vm, $('#knockoutArea')[0]);
        });
    });
    </script>
}

Source/WaterTreatment.Web/Views/DataEntry/Index.cshtml
@{
    ViewBag.Title = "Data Entry - In Progress Reports";
}
<div class="container-fluid" style="padding-top: 1.0em" id="knockout-area">
    <div class="row">
        <div class="col-md-2" style="padding-top: 0.4em">
            <label>Report Type</label>
        </div>
        <div class="col-md-10 form-group">
            <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default">
                    <input type="radio" name="type" value="Measurement" data-bind="checked: filters.Type, bsChecked: filters.Type" />Measurement
                </label>
                <label class="btn btn-default">
                    <input type="radio" name="type" value="Independent Quality Assurance" data-bind="checked: filters.Type, bsChecked: filters.Type" />Independent Quality Assurance
                </label>
                <label class="btn btn-default">
                    <input type="radio" name="type" value="Both" data-bind="checked: filters.Type, bsChecked: filters.Type" />Both
                </label>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="inset-container row">
            <div>
                @Html.Partial("_PagerControls")
                <div class="pull-left form-inline" style="margin-top: 1em;">
                    <span class="form-group pager-text"><strong>In Progress Reports</strong> <span style="display: none;" data-bind="visible: pager.totalResults() > 0">(<span data-bind="text: pager.totalResults"></span>)</span></span>
                </div>
            </div>
            <div>
                @Html.Partial("_PagerSpinner")
                <table class="table striped-grid">
                    <thead>
                        <tr class="branded-header">
                            <th>
                                <a href="#" data-bind="click: function() { pager.sort('Site') }">Site</a>
                                <i data-bind="attr: { class: pager.sortArrow('Site') }"></i>
                            </th>
                            <th>
                                <a href="#" data-bind="click: function() { pager.sort('Type') }">Type</a>
                                <i data-bind="attr: { class: pager.sortArrow('Type') }"></i>
                            </th>
                            <th>
                                Started
                            </th>
                            <th>
                                Copied From
                            </th>
                            <th>
                                Days Elapsed
                            </th>
                            <th colspan="2">
                                Actions
                            </th>
                        </tr>
                    </thead>
                    <tbody data-bind="foreach: { data: reports, as: '$report' }">
                        <tr data-bind="css: $parent.statusClass($report)">
                            <td>
                                <a data-bind="text: $report.Site, attr: { href: '/DataEntry/Edit/' + $report.Id }"></a>
                            </td>
                            <td>
                                <span data-bind="text: $report.Type"></span>
                            </td>
                            <td>
                                <span data-bind="text: $report.StartedOn"></span>
                            </td>
                            <td>
                                <span data-bind="text: $report.Copied"></span>
                            </td>
                            <td>
                                <span data-bind="text: $report.DaysElapsed"></span>
                            </td>
                            <td style="vertical-align: middle;" width="34">
                                <div class="data-entry-actions-edit" style="text-align: center; width: 100%; position: relative;">
                                    <a data-bind="attr: { href: '/DataEntry/Edit/' + $report.Id }">
                                        <span>
                                            <i class="btn btn-sm fa fa-pencil-square-o"></i>
                                        </span>
                                    </a>
                                </div>
                            </td>
                            <td width="34">
                                <div style="position: relative">
                                    <button class="btn btn-default fa fa-trash data-entry-actions-delete" data-bind="enable: !$root.isProcessingRequest(), click: $root.delete" title="Delete"></button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div>
                @Html.Partial("_PagerControls")
            </div>
        </div>  
    </div>  
    @Html.AntiForgeryToken()
</div>
@section Scripts
{
<script type="text/javascript">
require(['jquery', 'knockout', 'App/ViewModels/DataEntry/index', 'bootstrap', 'bootstrap-multiselect'], function ($, ko, ViewModel) {
    $(document).ready(function () {
        ko.applyBindings(new ViewModel(@Html.Raw(ViewBag.Sites)), $('#knockout-area')[0]);
    });
});
</script>
}

Source/WaterTreatment.Web/Views/DataEntry/Submit.cshtml
@model WaterTreatment.Web.Models.ViewReportModel
@{
    ViewBag.Title = "Continue Report";
}
<div class="container-fluid">
    @using (Html.BeginForm("Submit", "DataEntry", new { }, FormMethod.Post, new { @class = "form", id = "submitForm" }))
    {
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.AntiForgeryToken()
        <div class="row" style="padding-bottom: 1.0em;" id="knockout-submit-top">
            <div class="btn-group pull-right" role="group">
                <button type="button" class="btn btn-secondary" data-bind="click: edit, disable: isProcessingRequest">Edit</button>
                <button type="button" class="btn btn-primary" style="margin-left: 5px;" data-bind="click: submit, disable: isProcessingRequest">Submit</button>
            </div>
        </div>
        @Html.Partial("_ReportViewer", Model)
        <div class="row" style="padding-bottom: 1.0em;">
            <div class="btn-group pull-right" role="group" id="knockout-submit-bottom">
                <button type="button" class="btn btn-secondary" data-bind="click: edit, disable: isProcessingRequest">Edit</button>
                <button type="button" class="btn btn-primary" style="margin-left: 5px;" data-bind="click: submit, disable: isProcessingRequest">Submit</button>
            </div>
        </div>
    }
</div>
@section Scripts
{
    <script type="text/javascript">
    require(["jquery", "knockout", "App/ViewModels/DataEntry/Submit"], function ($, ko, ViewModel) {

        $(document).ready(function () {
            var vm = new ViewModel(@Html.Raw(Model.Id));

            ko.applyBindings(vm, $('#knockout-submit-top')[0]);
            ko.applyBindings(vm, $('#knockout-submit-bottom')[0]);
        });
    });
    </script>
}